from turtleSort import bubbleSort
from turtleSort import insertionSort
from turtleSort import cycleSort
from turtleSort import funcs
from turtleSort import prep
from turtleSort import quickSort
from turtleSort import selectionSort
from turtleSort import mergeSort
from turtleSort import config
from turtleSort import main
from turtleSort import classes
